[versions]
# plugin
shadow = "9.3.0"
runPaper = "3.0.2"

# library
spigotApi = "1.16.5-R0.1-SNAPSHOT"
configLib = "4.8.0"
mariaDBConnectorJ = "3.5.7"
hikaricp = "7.0.2"
jdbi = "3.51.0"
flyway = "11.20.0"
jspecify = "1.0.0"
junit = "6.0.1"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }

[libraries]
# system
spigotApi = { module = "org.spigotmc:spigot-api", version.ref = "spigotApi" }

# config
configLib = { module = "de.exlll:configlib-yaml", version.ref = "configLib" }

# database
mariaDBConnectorJ = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariaDBConnectorJ"}
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
jdbiCore = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi" }
jdbiSqlobject = { module = "org.jdbi:jdbi3-sqlobject", version.ref = "jdbi" }
flywayCore = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flywayMysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }

# check
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
jdbi = [
    "jdbiCore",
    "jdbiSqlobject"
]

flyway = [
    "flywayCore",
    "flywayMysql"
]
