name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version. ex: x.x.x, x.x.x-SNAPSHOT'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build test for release
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build
        run: ./gradlew build
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          path: build/libs/

      - name: Publish to azisaba repo
        run: ./gradlew publish
        env:
          VERSION: ${{ github.event.inputs.version }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

      - name: Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: build/libs/*.jar
          generate_release_notes: true
